//*****************************************************************************
// pinmux.c
//
// configure the device pins for different peripheral signals
//
// Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/ 
// 
// 
//  Redistribution and use in source and binary forms, with or without 
//  modification, are permitted provided that the following conditions 
//  are met:
//
//    Redistributions of source code must retain the above copyright 
//    notice, this list of conditions and the following disclaimer.
//
//    Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the 
//    documentation and/or other materials provided with the   
//    distribution.
//
//    Neither the name of Texas Instruments Incorporated nor the names of
//    its contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
//  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
//  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
//  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
//  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
//  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
//  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
//  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
//  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
//  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//*****************************************************************************

// This file was automatically generated by the CC31xx PinMux Utility
// Version: 1.0.2
//
//*****************************************************************************

#include "pinmux.h"
#include "hw_types.h"
#include "hw_memmap.h"
#include "hw_gpio.h"
#include "pin.h"
#include "rom.h"
#include "rom_map.h"
#include "gpio.h"
#include "prcm.h"

/****************************************************************************
*函数名-Function:		void Uart_PinMuxConfig(void)
*描述- Description:		配置引脚映射(配置UART 的引脚和时钟)
*输入参数-Input:	None
*输出参数-output:	None
*注意事项-Note：	▲01)    ▲02)    ▲03)    ▲04)  
*****************************************************************************/
void Uart_PinMuxConfig(void)   // 配置引脚映射(配置UART 的引脚和时钟)
{
    // Enable Peripheral Clocks 
    //△库函数“PRCMPeripheralClkEnable”，请查阅“使用到的库函数说明”章节
    // 启用 UARTA0 外设模块时钟
    MAP_PRCMPeripheralClkEnable(PRCM_UARTA0, PRCM_RUN_MODE_CLK);

    //
    // Configure PIN_55 for UART0 UART0_TX
    //△库函数“PinTypeUART”，请查阅“使用到的库函数说明”章节
    //配置引脚 PIN_55 为 UART0_TX 功能引脚  
    MAP_PinTypeUART(PIN_55, PIN_MODE_3);

    //
    // Configure PIN_57 for UART0 UART0_RX
    //△库函数“PinTypeUART”，请查阅“使用到的库函数说明”章节
    //配置引脚 PIN_57 为 UART0_RX 功能引脚  
    MAP_PinTypeUART(PIN_57, PIN_MODE_3);
}


/****************************************************************************
*函数名-Function:		void Led_PinMuxConfig(void)
*描述- Description:		配置引脚映射(配置LED  GPIO的引脚和时钟)
*输入参数-Input:	None
*输出参数-output:	None
*注意事项-Note：	▲01)    ▲02)    ▲03)    ▲04)  
*****************************************************************************/
void Led_PinMuxConfig(void)  //配置引脚映射(配置LED  GPIO的引脚和时钟)
{
    //△库函数“PRCMPeripheralClkEnable”，请查阅“使用到的库函数说明”章节
    //启用GPIOA1外设模块时钟 
    MAP_PRCMPeripheralClkEnable(PRCM_GPIOA1, PRCM_RUN_MODE_CLK);

    //△库函数“PinTypeGPIO”，请查阅“使用到的库函数说明”章节
    //配置引脚PIN_64为GPIO 输出引脚  
    MAP_PinTypeGPIO(PIN_64, PIN_MODE_0, false);
    
    //△库函数“GPIODirModeSet”，请查阅“使用到的库函数说明”章节
    MAP_GPIODirModeSet(GPIOA1_BASE, 0x2, GPIO_DIR_MODE_OUT);


    // 配置引脚PIN_01为GPIO 输出引脚 
    MAP_PinTypeGPIO(PIN_01, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA1_BASE, 0x4, GPIO_DIR_MODE_OUT);


    // 配置引脚PIN_02为GPIO 输出引脚 
    MAP_PinTypeGPIO(PIN_02, PIN_MODE_0, false);
    MAP_GPIODirModeSet(GPIOA1_BASE, 0x8, GPIO_DIR_MODE_OUT);

}



/****************************************************************************
*函数名-Function:		void Button_PinMuxConfig(void)
*描述- Description:		配置引脚映射(配置SW2(Pin15--GPIO22)、SW3(Pin4--GPIO13)按键的引脚和时钟)
*输入参数-Input:	None
*输出参数-output:	None
*注意事项-Note：	▲01)    ▲02)    ▲03)    ▲04)  
*****************************************************************************/
void Button_PinMuxConfig(void)  //配置引脚映射(配置SW2(Pin15--GPIO22)、SW3(Pin4--GPIO13)按键的引脚和时钟)
{
	//启用GPIOA1、GPIOA2外设模块时钟 
	MAP_PRCMPeripheralClkEnable(PRCM_GPIOA1, PRCM_RUN_MODE_CLK);
	MAP_PRCMPeripheralClkEnable(PRCM_GPIOA2, PRCM_RUN_MODE_CLK);

	// 配置引脚PIN_04为GPIO 输出引脚 
	MAP_PinTypeGPIO(PIN_04, PIN_MODE_0, false);
	MAP_GPIODirModeSet(GPIOA1_BASE, 0x20, GPIO_DIR_MODE_IN);

	// 配置引脚PIN_15为GPIO 输出引脚 
	MAP_PinTypeGPIO(PIN_15, PIN_MODE_0, false);
	MAP_GPIODirModeSet(GPIOA2_BASE, 0x40, GPIO_DIR_MODE_IN);
			
}


/****************************************************************************
*函数名-Function:		void IIC_PinMuxConfig(void)
*描述- Description:		 配置引脚映射(配置IIC 的引脚和时钟)
*输入参数-Input:	None
*输出参数-output:	None
*注意事项-Note：	▲01)    ▲02)    ▲03)    ▲04)  
*****************************************************************************/
void IIC_PinMuxConfig(void) // 配置引脚映射(配置IIC 的引脚和时钟)
{
	// 启用 I2CA0 外设模块时钟
	MAP_PRCMPeripheralClkEnable(PRCM_I2CA0, PRCM_RUN_MODE_CLK);

	// 配置引脚 PIN_01 为 I2C_SCL 功能引脚  
	MAP_PinTypeI2C(PIN_01, PIN_MODE_1);
	// 配置引脚 PIN_02 为 I2C_SDA 功能引脚
	MAP_PinTypeI2C(PIN_02, PIN_MODE_1);
}




